# Generated by Django 5.0.6 on 2024-07-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('img_url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('closing_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
